FORMAT: 1A
HOST: https://embed.unmade.com/

# Unmade Customization APIs

We provide a set of APIs which allows Unmade technology to be embedded into an existing
e-commerce system, in a way that appears seamless to the end customer.

![Architecture](https://unmade.s3.amazonaws.com/docs/UnmadeArchitecture.png)

Unmade-powered products continue to be configured in the e-commerce system, but the PDP content
will be provided by the Unmade customization platform via an iframe themed to match the host site.

The integration can happen in two stages:

1) **Front-end integration**: Unmade provides an iframe endpoint per customizable product,
which communicates with the host site via a JavaScript
[postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) API.
The host website must implement a small amount of functionality to bridge between
the two systems (detailed below).

2) **Back-end integration**: When the customer purchases an Unmade-powered product, the e-commerce
system must communicate this information to Unmade using our RESTful API, so that we can send the
design to manufacture. We also provide an API to check on order status.


## Product [/v1/products/{slug}/{?price,ccy,locale}]

+ Parameters
    + slug - The product slug (often equal to the SKU)
    + price (number) - The price to display for the product
    + ccy - The ISO 4217 currency code corresponding to the `price`
    + locale (optional) - The locale to use in the user interface
        + Default: `en-GB`


### iframe endpoint [GET]

Use this as the source on an `iframe` element to embed an Unmade-powered product in an
external e-commerce website.

```
<iframe
  src="<URL>"
  frameborder="0"
  width="100%"
  height="500px"
  scrolling="no">
</iframe>
```

Certain actions performed by the customer in the iframe will result in events being sent to
the host website using the [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)
API. A JavaScript listener, such as the following, should be implemented on the host site:


```
window.addEventListener("message", receiveMessage, false);

function receiveMessage (event) {
  var origin = event.origin || event.originalEvent.origin;
  if (origin === "https://embed.unmade.com") {
    switch (event.data.type) {
        case 'save':
            addToCart(e.data.payload);
        case 'resize':
            resizeIFrame(e.data.payload);
        case 'click':
            openModal(e.data.payload);
        default:
            break;
    }
  }
}
```

The `addToCart` payload will include the same information as the Design API, described below.

The `resize` event will be fired if the iframe changes size, for example if it's embedded in a
website with a responsive design, and the customer resizes their browser. Implementation of
`resizeIFrame` is required for a seamless experience.

The `click` event will be fired if a UI element in the iframe has been clicked, and the intended
behaviour needs to be handled by the host page. The most common example of this is a Size Guide
button inside the iframe, which triggers a modal dialog box outside the iframe. In this case
`e.data.payload.clicked` would be set to `"sizing"`.

+ Response 200 (text/html)


## Design [/v1/designs/{design_id}/]

### Retrieve design [GET]

If you want to receive information on a saved design, for example to check on availability.

+ Parameters
    + design_id (uuid) - ID of the Design in the form of a uuid

+ Request
    + Headers

            Authorization: Token ABCDEF
            
+ Response 200 (application/json)

        {
            "id": "8a2b6517-e020-46fd-8cd0-ec441d4ac4b4",
            "product": "product url",
            "preview": "preview url",
            "description": "Customized Product in Black & White"
        }



## Orders [/v1/orders/]

Once an order has been placed on the e-commerce platform, the Unmade system should be notified
so we can send the design for manufacture.


### Create an Order [POST]

+ Request Order with optional partner data (application/json)
    + Headers

            Authorization: Token ABCDEF

    + Body

            {
                "reference": "YOUR ORDER REFERENCE",
                "partner_data": {
                    "example_po_number": "example_number",
                    "example_po_type": "example_value",
                    "example_shipping_method": "example_shipping_service"
                },
                "order_items": [
                    {
                        "design": "3cd42fe8-7491-11e8-adc0-fa7ae01bbebc",
                        "quantity": 2
                        "partner_data": {
                            "barcode": "98323928238372"
                        }
                    }
                ],
                "shipping_address": {
                    "name": "John Smith",
                    "company_name": "unmade",
                    "address_1": "152 Strand"
                    "address_2": "Somerset House",
                    "city": "London",
                    "country_area": "",
                    "postal_code": "WC2R 1LA",
                    "country": "UK",
                    "phone": ""
                }
            }

+ Response 201 (application/json)

        {
            "id": "c9b86945-45a6-4a43-beaf-361a7f0d8a77"
        }

+ Request Team wear order (application/json)
    + Headers

            Authorization: Token ABCDEF

    + Body

            {
                "reference": "YOUR ORDER REFERENCE",
                "partner_data": {
                    "example_po_number": "example_number",
                    "example_po_type": "example_value",
                    "example_shipping_method": "example_shipping_service"
                },
                "order_items": [
                    {
                        "design": "3cd42fe8-7491-11e8-adc0-fa7ae01bbebc",
                        "quantity": 2
                        "options" : {
                            "size": "L"
                        },
                        "partner_data": {
                            "barcode": "98323928238372"
                        }
                    },
                    {
                        "design": "3cd42fe8-7491-11e8-adc0-fa7ae01bbebc",
                        "quantity": 3
                        "options" : {
                            "size": "M"
                        },
                        "partner_data": {
                            "barcode": "98323928238372"
                        }
                    },
                    {
                        "design": "3cd42fe8-7491-11e8-adc0-fa7ae01bbebc",
                        "quantity": 1
                        "options" : {
                            "size": "S"
                        },
                        "partner_data": {
                            "barcode": "98323928238372"
                        }
                    }
                    
                ],
                "shipping_address": {
                    "name": "John Smith",
                    "company_name": "unmade",
                    "address_1": "152 Strand"
                    "address_2": "Somerset House",
                    "city": "London",
                    "country_area": "",
                    "postal_code": "WC2R 1LA",
                    "country": "UK",
                    "phone": ""
                }
            }

+ Response 201 (application/json)

        {
            "id": "25f5bcd3-ace3-4272-956b-f78fe55ab8f1"
        }


## Order [/v1/orders/{order_id}/]

### Retrieve an existing order [GET]

If you want to receive information on an order, for example to check on status.

+ Parameters
    + order_id (uuid) - ID of the Order in the form of a uuid

+ Request
    + Headers

            Authorization: Token ABCDEF

+ Response 200 (application/json)

        {
            "id": "25f5bcd3-ace3-4272-956b-f78fe55ab8f1",
            "reference": "partner_order_reference",
            "created": "2018-04-11T17:20:04.991263Z",
            "partner_data":{
                "customer_po_number": "1234512334X",
            },
            "shipping_address" : {
                "name": "John Smith",
                "company_name": "unmade",
                "address_1": "152 Strand"
                "address_2": "Somerset House",
                "city": "London",
                "country_atera": "",
                "postal_code": "WC2R 1LA",
                "country": "UK",
                "phone": ""
            },
            "order_items": [
                {
                    "design": "3cd42fe8-7491-11e8-adc0-fa7ae01bbebc",
                    "quantity": 1,
                    "partner_data": {
                        "barcode": "98323928238372"
                    },
                },
                {
                    "design": "44dcbb2e-7491-11e8-adc0-fa7ae01bbebc",
                    "quantity": 3,
                    "partner_data": {
                        "barcode": "98329845228372"
                    },
                },
            ]
        }