version: '3.4'

services:

    dev:
        image: "funbox/blueprinter"
        command: -i apiary.apib -s -p 3000
        volumes:
            - .:/app
        ports:
          - "3000:3000"
          - "3001:3001"

    render:
        image: "funbox/blueprinter"
        command: -i apiary.apib -o index.html --favicon images/favicon.png
        volumes:
            - .:/app
